# Interaction weights (EngagementScore)
DEFAULT_WEIGHT_VIEW = 0.01
DEFAULT_WEIGHT_LIKE = 1.0
DEFAULT_WEIGHT_COMMENT = 2.0
DEFAULT_WEIGHT_SAVE = 3.0
DEFAULT_WEIGHT_SHARE = 5.0

# Platform multipliers
DEFAULT_PLATFORM_WEIGHT_TIKTOK = 1.0
DEFAULT_PLATFORM_WEIGHT_FACEBOOK = 1.2
DEFAULT_PLATFORM_WEIGHT_YOUTUBE = 1.5
DEFAULT_PLATFORM_WEIGHT_INSTAGRAM = 1.1
DEFAULT_PLATFORM_WEIGHT_UNKNOWN = 1.0

# Sentiment amplifiers
DEFAULT_AMP_NEGATIVE = 1.5
DEFAULT_AMP_NEUTRAL = 1.0
DEFAULT_AMP_POSITIVE = 1.1

# Thresholds
DEFAULT_VIRAL_THRESHOLD = 70.0
DEFAULT_KOL_FOLLOWER_THRESHOLD = 50000
DEFAULT_MAX_RAW_SCORE_CEILING = 100000.0

# Platform names
PLATFORM_TIKTOK = "TIKTOK"
PLATFORM_FACEBOOK = "FACEBOOK"
PLATFORM_YOUTUBE = "YOUTUBE"
PLATFORM_INSTAGRAM = "INSTAGRAM"
PLATFORM_UNKNOWN = "UNKNOWN"

# Sentiment labels
SENTIMENT_NEGATIVE = "NEGATIVE"
SENTIMENT_NEUTRAL = "NEUTRAL"
SENTIMENT_POSITIVE = "POSITIVE"

# Risk levels
RISK_CRITICAL = "CRITICAL"
RISK_HIGH = "HIGH"
RISK_MEDIUM = "MEDIUM"
RISK_LOW = "LOW"

# Impact thresholds for risk calculation
IMPACT_HIGH_THRESHOLD = 70.0
IMPACT_MEDIUM_THRESHOLD = 40.0
IMPACT_HIGH_NON_NEGATIVE_THRESHOLD = 60.0

# Verified bonus multiplier
VERIFIED_BONUS_MULTIPLIER = 1.2

# Score limits
SCORE_MIN = 0.0
SCORE_MAX = 100.0

# Input field names
FIELD_VIEWS = "views"
FIELD_LIKES = "likes"
FIELD_COMMENTS_COUNT = "comments_count"
FIELD_SHARES = "shares"
FIELD_SAVES = "saves"
FIELD_FOLLOWERS = "followers"
FIELD_IS_VERIFIED = "is_verified"
FIELD_LABEL = "label"

# Output field names
OUTPUT_IMPACT_SCORE = "impact_score"
OUTPUT_RISK_LEVEL = "risk_level"
OUTPUT_IS_VIRAL = "is_viral"
OUTPUT_IS_KOL = "is_kol"
OUTPUT_IMPACT_BREAKDOWN = "impact_breakdown"
OUTPUT_ENGAGEMENT_SCORE = "engagement_score"
OUTPUT_REACH_SCORE = "reach_score"
OUTPUT_PLATFORM_MULTIPLIER = "platform_multiplier"
OUTPUT_SENTIMENT_AMPLIFIER = "sentiment_amplifier"
OUTPUT_RAW_IMPACT = "raw_impact"

__all__ = [
    "DEFAULT_WEIGHT_VIEW",
    "DEFAULT_WEIGHT_LIKE",
    "DEFAULT_WEIGHT_COMMENT",
    "DEFAULT_WEIGHT_SAVE",
    "DEFAULT_WEIGHT_SHARE",
    "DEFAULT_PLATFORM_WEIGHT_TIKTOK",
    "DEFAULT_PLATFORM_WEIGHT_FACEBOOK",
    "DEFAULT_PLATFORM_WEIGHT_YOUTUBE",
    "DEFAULT_PLATFORM_WEIGHT_INSTAGRAM",
    "DEFAULT_PLATFORM_WEIGHT_UNKNOWN",
    "DEFAULT_AMP_NEGATIVE",
    "DEFAULT_AMP_NEUTRAL",
    "DEFAULT_AMP_POSITIVE",
    "DEFAULT_VIRAL_THRESHOLD",
    "DEFAULT_KOL_FOLLOWER_THRESHOLD",
    "DEFAULT_MAX_RAW_SCORE_CEILING",
    "PLATFORM_TIKTOK",
    "PLATFORM_FACEBOOK",
    "PLATFORM_YOUTUBE",
    "PLATFORM_INSTAGRAM",
    "PLATFORM_UNKNOWN",
    "SENTIMENT_NEGATIVE",
    "SENTIMENT_NEUTRAL",
    "SENTIMENT_POSITIVE",
    "RISK_CRITICAL",
    "RISK_HIGH",
    "RISK_MEDIUM",
    "RISK_LOW",
    "IMPACT_HIGH_THRESHOLD",
    "IMPACT_MEDIUM_THRESHOLD",
    "IMPACT_HIGH_NON_NEGATIVE_THRESHOLD",
    "VERIFIED_BONUS_MULTIPLIER",
    "SCORE_MIN",
    "SCORE_MAX",
    "FIELD_VIEWS",
    "FIELD_LIKES",
    "FIELD_COMMENTS_COUNT",
    "FIELD_SHARES",
    "FIELD_SAVES",
    "FIELD_FOLLOWERS",
    "FIELD_IS_VERIFIED",
    "FIELD_LABEL",
    "OUTPUT_IMPACT_SCORE",
    "OUTPUT_RISK_LEVEL",
    "OUTPUT_IS_VIRAL",
    "OUTPUT_IS_KOL",
    "OUTPUT_IMPACT_BREAKDOWN",
    "OUTPUT_ENGAGEMENT_SCORE",
    "OUTPUT_REACH_SCORE",
    "OUTPUT_PLATFORM_MULTIPLIER",
    "OUTPUT_SENTIMENT_AMPLIFIER",
    "OUTPUT_RAW_IMPACT",
]
