# Redis Defaults
DEFAULT_HOST = "localhost"
DEFAULT_PORT = 6379
DEFAULT_DB = 0
DEFAULT_SSL = False
DEFAULT_ENCODING = "utf-8"
DEFAULT_DECODE_RESPONSES = True
DEFAULT_MAX_CONNECTIONS = 50
DEFAULT_SOCKET_TIMEOUT = 5
DEFAULT_SOCKET_CONNECT_TIMEOUT = 5
DEFAULT_SOCKET_KEEPALIVE = True
DEFAULT_HEALTH_CHECK_INTERVAL = 30

# Error Messages
ERROR_HOST_EMPTY = "host is required"
ERROR_INVALID_PORT = "port must be between 1 and 65535"
ERROR_INVALID_DB = "db must be >= 0"
ERROR_INVALID_MAX_CONNECTIONS = "max_connections must be > 0"
ERROR_INVALID_SOCKET_TIMEOUT = "socket_timeout must be > 0"
