# outbox/constant.py

TABLE_NAME = "analytics_outbox"
RELAY_BATCH_SIZE = 50
RELAY_INTERVAL_SECONDS = 5
RETENTION_DAYS = 7

__all__ = ["TABLE_NAME", "RELAY_BATCH_SIZE", "RELAY_INTERVAL_SECONDS", "RETENTION_DAYS"]
