apiVersion: v1
kind: Secret
metadata:
  name: analysis-secrets
  namespace: smap
  labels:
    app.kubernetes.io/name: analysis
    app.kubernetes.io/part-of: smap
type: Opaque
stringData:
  # PostgreSQL Configuration
  DB_USER: "smap_analysis"
  DB_PASSWORD: "analysis_pwd"

  # Redis Configuration
  REDIS_PASSWORD: "21042004"

  # MinIO Configuration
  MINIO_ACCESS_KEY: "tantai"
  MINIO_SECRET_KEY: "21042004"
