"""Spam constants."""

MENTION_SPAM_THRESHOLD_DEFAULT: float = 0.65
AUTHOR_INORGANIC_THRESHOLD_DEFAULT: float = 0.65
BURST_WINDOW_MINUTES_DEFAULT: int = 60

__all__ = [
    "MENTION_SPAM_THRESHOLD_DEFAULT",
    "AUTHOR_INORGANIC_THRESHOLD_DEFAULT",
    "BURST_WINDOW_MINUTES_DEFAULT",
]
