# Aspect categories
ASPECT_DESIGN = "DESIGN"
ASPECT_PERFORMANCE = "PERFORMANCE"
ASPECT_PRICE = "PRICE"
ASPECT_SERVICE = "SERVICE"
ASPECT_GENERAL = "GENERAL"

# Default configuration values
DEFAULT_ASPECT_DICTIONARY_PATH = None
DEFAULT_ENABLE_AI = True
DEFAULT_AI_THRESHOLD = 5
DEFAULT_MAX_KEYWORDS = 30

# Keyword sources
SOURCE_DICT = "DICT"
SOURCE_AI = "AI"

# Scores
SCORE_DICT_MATCH = 1.0

# Keyword types from SpacyYake
KEYWORD_TYPE_STATISTICAL = "statistical"
KEYWORD_TYPE_ENTITY_PREFIX = "entity"
KEYWORD_TYPE_CHUNK = "chunk"

# Dictionary structure keys
DICT_KEY_PRIMARY = "primary"
DICT_KEY_SECONDARY = "secondary"

# File encoding
FILE_ENCODING_UTF8 = "utf-8"

# Metadata keys
METADATA_DICT_MATCHES = "dict_matches"
METADATA_AI_MATCHES = "ai_matches"
METADATA_TOTAL_KEYWORDS = "total_keywords"
METADATA_TOTAL_TIME_MS = "total_time_ms"

# Output keys
OUTPUT_KEYWORD = "keyword"
OUTPUT_ASPECT = "aspect"
OUTPUT_SCORE = "score"
OUTPUT_SOURCE = "source"

__all__ = [
    "ASPECT_DESIGN",
    "ASPECT_PERFORMANCE",
    "ASPECT_PRICE",
    "ASPECT_SERVICE",
    "ASPECT_GENERAL",
    "DEFAULT_ASPECT_DICTIONARY_PATH",
    "DEFAULT_ENABLE_AI",
    "DEFAULT_AI_THRESHOLD",
    "DEFAULT_MAX_KEYWORDS",
    "SOURCE_DICT",
    "SOURCE_AI",
    "SCORE_DICT_MATCH",
    "KEYWORD_TYPE_STATISTICAL",
    "KEYWORD_TYPE_ENTITY_PREFIX",
    "KEYWORD_TYPE_CHUNK",
    "DICT_KEY_PRIMARY",
    "DICT_KEY_SECONDARY",
    "FILE_ENCODING_UTF8",
    "METADATA_DICT_MATCHES",
    "METADATA_AI_MATCHES",
    "METADATA_TOTAL_KEYWORDS",
    "METADATA_TOTAL_TIME_MS",
    "OUTPUT_KEYWORD",
    "OUTPUT_ASPECT",
    "OUTPUT_SCORE",
    "OUTPUT_SOURCE",
]
